### ISSUE TITLE
Check rlpx for EIP-8 compliance

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-eth#109]
Check if rlpx complies with EIP-8 and create unit tests with these test vectors:
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-8.md#test-vectors

This was done already for the discovery part.

**Comment by cheatfate** [comment]
This two procedures are already supporting EIP-8 authentication and perform it transparently.
https://github.com/status-im/nim-eth/blob/master/eth/p2p/auth.nim#L436
https://github.com/status-im/nim-eth/blob/master/eth/p2p/auth.nim#L456

Test vectors from link you mentioned already in test suite.
https://github.com/status-im/nim-eth/blob/master/tests/p2p/test_auth.nim#L95-L96

**Comment by kdeme** [comment]
Oh that's great! I should have known that you would have looked into that :)

I did add one little check that seems to be forgotten: https://github.com/status-im/nim-eth/pull/112
