### ISSUE TITLE
P2P protocol backwards compatibility 

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-eth#116]
Currently the `proc`s of a `p2pProtocol` will allow for parsing rlp that contains more fields than there are parameters. This is good as it allows for EIP-8 test vectors to pass.

However, the other way around does not work. When our protocol adds certain parameters to a `proc` in a newer version, then running against an older version will make it fail. 
It would be nice if we could provide a fallback to a lower version.

It could perhaps be done by having some `optional` parameters in a `proc`, and then within that `proc` it could be decided how to continue (be compatible or not...).

This would be specifically handy in the handshake for https://github.com/status-im/nim-eth/pull/114.

**Comment by kdeme** [comment]
Well, in my opinion, the "cleanest" way to create the suggested Waku mode (https://github.com/status-im/specs/pull/54) would be to extend to the Whisper handshake. This basically is an upgrade of the protocol definition as explained above and serves as a good example.

It could also be implemented by not sending this information in the handshake but in separate message types why would be send after the handshake completed. But I believe that to be less ideal.

**Comment by kdeme** [comment]
Yeah, good point, same thought has passed my mind. It is not nice to have the code cluttered with version checks and certain parameter checks to do this or that. Main tasks of the messages should be remain as clear and simple as possible. I guess this problem would occur in my suggestion with the `optional` parameters. And while with the example of `Waku` mode it would not be that bad, things could get ugly after so many updates.

So different `proc`s per protocol version (at least if it matters for that `proc`) or a whole new definition per protocol version (perhaps that actually already works now? I haven't tried this.) would be cleaner. You can easily separate them (perhaps per file even). And also easily throw away old versions when you decide to stop supporting them.

**Comment by kdeme** [comment]
So, it turns out that this is not just about compatiblity between versions. But we might need optional parameters within a version, see discussion: https://github.com/status-im/specs/pull/60#issuecomment-558933780

Although it could be debated if that is really necessary.

**Comment by zah** [comment]
Does the comment above suggest that the DevP2P back-end should support optional parameters in the messages? This would require some changes in the serialization and deserialization routines.

**Comment by kdeme** [comment]
Yes, that is what is suggests. In fact, this is already in the EIP-627 Whisper spec. The bloom filter there is mentioned as optional. And within geth (not spec), the light client config too.

**Comment by kdeme** [comment]
I think we can close this issue.
All the different concerns that passed the revue here are basically written down in following issues:
- https://github.com/status-im/nim-eth/issues/136
- https://github.com/status-im/nim-eth/issues/140
- https://github.com/status-im/nim-eth/issues/150
