### ISSUE TITLE
Use custom hash function for eth1 ecdh

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-eth#222]
We currently extend upstream libsecp256k1 to add a `secp256k1_ecdh_raw` function - since this was implemented, upstream has added the ability do do custom hash functions that could be used to implement this ethereum-specific way of deriving keys - as such, we can stop patching upstream and move the logic into `nim-eth`.

Upstream discussion:
https://github.com/bitcoin-core/secp256k1/issues/352

Implementation blueprint:
https://github.com/bitcoin-core/secp256k1/blob/master/src/modules/ecdh/tests_impl.h#L18-L25

**Comment by cheatfate** [comment]
This issue is not yet fixed.
