### ISSUE TITLE
duplicate connections when incoming vs outgoing connect

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-eth#36]
It's possible to have multiple connections with the same `Peer`:

Easy scenario:
1. Peer A connects to peer B (outgoing connection from Peer A): connection successful
2. Peer B connects to peer A (incoming connection to Peer B): connection is set-up but a `disconnect` is done due to duplicate connection. Remove peer from `peer_pool.connectedNodes` is done.
3. Peer A remains connected to B (connection from step 1)
4. Peer A connects again to peer B (outgoing connection Peer A): connection is set-up as peer B is no longer in `connectedNodes`

I think the same is possible with first an incoming connection for Peer A and next an outgoing. It is just more difficult to achieve as there is an initial check here: https://github.com/status-im/nim-eth/blob/master/eth/p2p/peer_pool.nim#L62 
However, due to the async behaviour of `rlpxConnect` and `rlpxAccept`, I think this could still occur the other way around.

To resolve this the following could be done:
Do not let the `disconnect` call remove the peer from the `connectedNodes` in the peer pool in case `DisconnectionReason` is `AlreadyConnected`.

Other options are to check within `rlpxAccept` and `rlpxConnect` itself if the node is already in `connectedNodes` or `connectingNodes`. By the way, in case of an incoming connection, `connectingNodes` is never set, it is true however that in this case the actual node (pub key) is known much later. Also, even when moving the check to `rlpxAccept` and `rlpxConnect`, there is still a chance to have the problem will occur (due to the last await) unless the `connectedNodes` add is moved right after the check.

So I guess the question basically is, in case of duplicate connection: Do we allow the full connection (including all sub protocol connection handlers) to happen and then afterwards need to disconnect (including running all sub protocol disconnection handlers). Or do we just stop `rlpxAccept` or `rlpxConnect` the moment we know it is a duplicate peer (e.g. before `postHelloSteps`)? The latter will be more intrusive as change.

Thoughts?

**Comment by yglukhov** [comment]
IMO, it's reasonable to trigger `AlreadyConnected` as soon as we can, no need to do the subproto handshakes.
