### ISSUE TITLE
Add single `toSzzType` definition for all basic ssz types

### ISSUE THREAD

**Issue by KonradStaniec** [status-im/nim-eth#391]
According to https://github.com/status-im/nimbus-eth1/pull/791#discussion_r688740344, adding catch all `toSzzType`  definition to `eth/ssz/ssz_serialization.nim` would  unburden users of library from creating unnecessary mapping.

**Comment by arnetheduck** [comment]
Catch-all definitions are hard to debug in nim and tend to introduce subtle runtime issues where, for a type that _has_ an overload, sometimes the catch-all is used and sometimes the overload is used because of import problems - it's generally a good idea to generally avoid catch-alls and be explicit about supported types instead.

**Comment by arnetheduck** [comment]
cc @zah - how can we avoid them in general? I'm not sure why, but we're using `toSszType(auto)` when we could be more specific - for example, `toSszType[T: object|tuple]` would defer to the fields, and this should "fit" in the core library, while still permitting more specific overloads.

**Comment by KonradStaniec** [comment]
I think the case here is that it would be ideal if the user of the library would not need to define `toSszType` when he is using primitive types i.e currently if one have
```
let a = List.init(@[1'u8], 2048)
let enc = SSZ.encode(a)
```
it ends with `Error: undeclared identifier: 'toSszType'` which kinda forces user to define this `toSszType(auto)` templates.

I am not yet sure what is best solution here but `for a type that has an overload, sometimes the catch-all is used and sometimes the overload is used because of import problems` sounds pretty scary so yea it should probably be better thought that simple catch all.

**Comment by arnetheduck** [comment]
> I think the case here is that it would be ideal if the user of the library would not need to define toSszType when he is using primitive types i.e currently if one have

indeed - the core ssz library would need to define `toSszType` for all identity conversions for primitive ssz types that appear in the spec.

**Comment by zah** [comment]
In the original SSZ library, the catch all definition simply fails for the unsupported types, so everything is fine. You can apply the same principle here. In general, I've avoided the overload-heavy style of defining these operations wherever this makes sense, because this leads to more concise and easier to read error messages when a particular overload is missing (i.e. the error messages display mostly overloads defined by the user).

**Comment by arnetheduck** [comment]
> simply fails for the unsupported types

in the case of `toSszType` it doesn't fail though - it just passes it on to the next level - this means that if I declare a `toSszType`, it might or might not get used, depending on how well the "next level" works with the resulting type

**Comment by zah** [comment]
Right, I should clarify how it works. Any value passed through `toSszType` is then passed to another SSZ function that requires the resulting type to be one of the built-in SSZ types. So, if your `toSszType` overload is not picked up, you'll end up in an error in the next layer. The error is something along the lines of "SSZ serialization of the type Foo is not supported".

It would be OK to restrict what can pass through `toSszType`, but the catch all overload is also an opportunity to transform the generic "no overload found" error into a more specific error message with instructions for the user explaining how to extend the library for additional types.

**Comment by arnetheduck** [comment]
> is also an opportunity to transform the generic "no overload found" error into a more specific error 

```
func toSszType(v: auto): auto = {.error: "Overload toSszType for your distinct types!.}
```

what about that?

**Comment by zah** [comment]
Right now, I would say that it's not clear how (or whether) this interception is better than the existing `unsupported T` helper which gets activated in consistent way regardless of which surface API you are using. Some examples demonstrating different error messages could help. Admittedly, the error message produced by `unsupported T` right now is not perfect, but it can be modified to explain how `toSszType` and `fromSszBytes` must be overloaded for user types.

**Comment by arnetheduck** [comment]
well, it's somewhat equivalent - ie you can still use `unsupported T` in this overload instead of `error` to produce a similar error message - the point however is to catch the error as early as possible in a place related to what the user should be doing (ie "missing overload of toSszType") rather than somewhere deeper ("can't compile isFixedSize because ...")` that is unrelated - that seems more .. healthy generally.

**Comment by zah** [comment]
The user never calls `toSszType` directly, so "catch the error in a place related to what the user should be doing" is not a convincing argument. As I said, we should compare the specific error messages produced by some of the surface APIs.

**Comment by arnetheduck** [comment]
```
stack trace: (most recent call last)
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/types.nim(380, 9) unsupported
/home/arnetheduck/status/nimbus-eth2/beacon_chain/spec/helpers.nim(116, 17) template/generic instantiation of `hash_tree_root` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(689, 23) template/generic instantiation of `hashTreeRootAux` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(552, 20) template/generic instantiation of `merkleizeFields` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(553, 8) template/generic instantiation of `enumerateSubFields` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/types.nim(521, 33) template/generic instantiation of `enumInstanceSerializedFields` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(554, 18) template/generic instantiation of `addField` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(402, 30) template/generic instantiation of `hash_tree_root` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(689, 23) template/generic instantiation of `hashTreeRootAux` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(558, 17) template/generic instantiation of `unsupported` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/types.nim(380, 9) Error: SSZ serialization of the type Version = distinct array[4, byte] is not supported
```

```
/home/arnetheduck/status/nimbus-eth2/beacon_chain/spec/helpers.nim(116, 17) template/generic instantiation of `hash_tree_root` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(552, 20) template/generic instantiation of `merkleizeFields` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(553, 8) template/generic instantiation of `enumerateSubFields` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/types.nim(521, 33) template/generic instantiation of `enumInstanceSerializedFields` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(554, 18) template/generic instantiation of `addField` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(402, 30) template/generic instantiation of `hash_tree_root` from here
/home/arnetheduck/status/nimbus-eth2/beacon_chain/ssz/merkleization.nim(689, 32) Error: type mismatch: got <Version>
but expected one of: 
template toSszType(v: BasicType): auto
  first type mismatch at position: 1
  required type for v: BasicType
  but expression 'x' is of type: Version
template toSszType(v: BitArray): auto
  first type mismatch at position: 1
  required type for v: BitArray
  but expression 'x' is of type: Version
template toSszType(v: BitList): auto
  first type mismatch at position: 1
  required type for v: BitList
  but expression 'x' is of type: Version
template toSszType(v: HashArray): auto
  first type mismatch at position: 1
  required type for v: HashArray
  but expression 'x' is of type: Version
template toSszType(v: HashList): auto
  first type mismatch at position: 1
  required type for v: HashList
  but expression 'x' is of type: Version
template toSszType(v: List): auto
  first type mismatch at position: 1
  required type for v: List
  but expression 'x' is of type: Version
template toSszType(v: array): auto
  first type mismatch at position: 1
  required type for v: array
  but expression 'x' is of type: Version
template toSszType(v: enum): auto
  first type mismatch at position: 1
  required type for v: enum
  but expression 'x' is of type: Version
template toSszType(v: object): auto
  first type mismatch at position: 1
  required type for v: object
  but expression 'x' is of type: Version
template toSszType(v: seq[byte]): seq[byte]
  first type mismatch at position: 1
  required type for v: seq[byte]
  but expression 'x' is of type: Version
template toSszType(v: tuple): auto
  first type mismatch at position: 1
  required type for v: tuple
  but expression 'x' is of type: Version
template toSszType(x: Eth2Digest): auto
  first type mismatch at position: 1
  required type for x: Eth2Digest
  but expression 'x' is of type: Version

expression: toSszType(x)
```


here's without a fancy catch-all with error - it turns out we cannot overload both `object` and `auto` at the same time due to bugs.

**Comment by arnetheduck** [comment]
> The user never calls toSszType directly, 

the user (of the ssz library) has to *implement* toSszType directly

**Comment by zah** [comment]
The short version of the error message has better signal-to-noise ratio for me. Especially if we put a link to the documentation explaining how user-defined types are integrated with the library.

**Comment by arnetheduck** [comment]
see https://github.com/status-im/nimbus-eth2/pull/2785/files#diff-fb361899bb37d36239aa58df4ec5456ed52eda137af5cfddb9cd2eb2678c93e7R236 for a version that provides both strictness and documentation

**Comment by kdeme** [comment]
Closing issue, above mentioned version is now commonly used from nim-ssz-serialization
