### ISSUE TITLE
Observer onPeerDisconnected run when it shouldn't

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-eth#46]
There is the possibility that the `onPeerDisconnected` call of an `PeerObserver` is called when it shouldn't. That is, when the `onPeerConnected` never got called.

This is because `removePeer` is run in `disconnect`, and disconnect can get called already in `rlpxConnect` or rlpxAccept`, e.g. https://github.com/status-im/nim-eth/blob/master/eth/p2p/rlpx.nim#L1347

This issue gets quick-fixed here: https://github.com/status-im/nim-eth/pull/45/commits/2174a7b99a4a70bbd19b9a5fff62822a1e236aec

But, it is already the second time that I see a problem because `removePeer` should not be run.  So perhaps an architectural change would be better.

**Comment by stefantalpalaru** [comment]
Fixed by https://github.com/status-im/nim-eth/pull/74
