### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by galadd** [status-im/nim-eth#648]
The test aren't passing. With eth_trie, its error is from binaries.nim

```bash
Building and running: tests/trie/all_tests
/home/admin/nim-eth/eth/trie/binaries.nim(111, 38) Error: undeclared field: 'baseAddr' for type binaries.TrieNodeKey [type declared in /home/admin/nim-eth/eth/trie/binaries.nim(12, 3)]
```

**Comment by jangko** [comment]
binary trie is an experimental module and never used after it's creation. it is ok to remove it from test.

**Comment by galadd** [comment]
I think baseAddr was initially declared and was removed down the line. I made some changes I am not sure I am supposed to make and it seems to work on my end. I will see if there is any effect. 

Leaving this issue open till I get others figured out
