### ISSUE TITLE
eth_protocol handshake with Parity clients always results in a timeout

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-eth#75]
When monitoring nimbus I often noticed a disconnection during `rlpxConnect`.
Turns out this is due to a timeout on the `eth_protocol` handshake.
Further debugging has shown that this occurs almost always with Parity clients.
In fact, so far, I've never seen a successful connection with a Parity client, and I've also tested this locally by starting one myself and trying to connect to it.

**Comment by zah** [comment]
Some simple reproduction steps will be helpful here.

**Comment by kdeme** [comment]
1. Run parity client locally.
2. Run nimbus with --staticnodes with enode info of local parity client
3. Will fail with timeout in connection handler.

I did add some extra traces in Nimbus to see this better. I can push this in a PR.
You can also see it when just running Nimbus (with these extra traces).

I'm investigating the issue atm. Looks like the Parity client errors when receiving the hello message from Nimbus. Nimbus does receive the hello from Parity correctly. Hence the timeout on the next step (eth protocol handshake).

**Comment by kdeme** [comment]
Fixed in https://github.com/status-im/nim-eth/pull/77
