### ISSUE TITLE
'payloadBytesCount' in rlp.nim behaves differently on 32 bit vs 64 bit

### ISSUE THREAD

**Issue by jangko** [status-im/nim-eth#95]
I found ['payloadBytesCount' in eth/rlp.nim](https://github.com/status-im/nim-eth/blob/bef28a18e58f52f24bcc50f0cadefac0224d4630/eth/rlp.nim#L117) behaves differently when compiled to 32bit. The [spec](https://github.com/ethereum/wiki/wiki/RLP) doesn't say anything about decoding to platform dependent 'int'. 

it's a bit confusing whether to fail on 32 bit or 64 bit. need deeper investigation.

**Comment by zah** [comment]
It may be reasonable to switch the `payloadBytesCount` return type to `int64`, but where did you encounter such a large payload size? The intended current behaviour of the code is that it will fail with `UnsupportedRlpError` when the payload size is too large.

**Comment by jangko** [comment]
It was discovered during transaction test using synthetic rlp sequence from eth-test. The test indicates that the payload limit should be 32bit rather than 64bit.

The spec itself never mentions about the limit.

When I take a look at various implementations, here what I found:
- geth set the limit to 64bit
- py-evm implement it as big-int, no-limit
- ruby-ciri also use big-int
- java-ethereum provide both 32bit and 64bit version of decoder and each will raise exception if it reach respective limit. but for transaction codec, it use 32bit version.
- parity use the same implementation as current nim-eth `payloadBytesCount`, depends on the target int size it can be 32bit or 64bit

a good example of interpreting ambiguous spec.

**Comment by jangko** [comment]
btw, our current implementation also posses other subtle problem, it uses int rather than uint.
the algorithm only check the target byte size but ignoring the potential of int overflow.
we cannot depend on the compiler to raise overflow exception in this case.

**Comment by jangko** [comment]
closing. the ambiguity should be handled by the test runner.
